version: '2'
services:
  plates-app:
    image: plates
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://plates-mariadb:3306/plates?useLegacyDatetimeCode=false&serverTimezone=UTC
      - freedata_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://plates-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://plates-elasticsearch:9200
    ports:
      - 8080:8080
  plates-mariadb:
    extends:
      file: mariadb.yml
      service: plates-mariadb
  plates-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: plates-elasticsearch
