version: '2'
services:
  plates-mariadb:
    image: mariadb:10.5.3
    # volumes:
    #     - ~/volumes/freedata/Plates/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=plates
      - MYSQL_ROOT_PASSWORD=Plates12345678
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
